src/cliente/urls.py
from django.urls import path
from .views import index
from .views_models import transportista, paquete, cotizacion, flete


app_name = 'cliente'


urlpatterns = [
    path('', index, name='index'),
    path('transportista/list/', transportista.TransportistaListView.as_view(), name='transportista_list'),
    path('transportista/create/', transportista.TransportistaCreateView.as_view(), name='transportista_create'),
    path('transportista/update/<int:pk>', transportista.TransportistaUpdateView.as_view(), name='transportista_update'),
    path('transportista/detail/<int:pk>', transportista.TransportistaDetailView.as_view(), name='transportista_detail'),
    path('transportista/delete/<int:pk>', transportista.TransportistaDeleteView.as_view(), name='transportista_delete'),
    path('paquete/list/', paquete.paquete_list, name='paquete_list'),  # Asegúrate de que esta línea es correcta
    path('paquete/create/', paquete.paquete_create, name='paquete_create'),
    path('paquete/update/<int:pk>', paquete.paquete_update, name='paquete_update'),
    path('paquete/detail/<int:pk>', paquete.paquete_detail, name='paquete_detail'),
    path('paquete/delete/<int:pk>', paquete.paquete_delete, name='paquete_delete'),
    path('cotizacion/list/', cotizacion.cotizacion_list, name='cotizacion_list'),
    path('cotizacion/create/', cotizacion.cotizacion_create, name='cotizacion_create'),
    path('cotizacion/update/<int:pk>', cotizacion.cotizacion_update, name='cotizacion_update'),
    path('cotizacion/detail/<int:pk>', cotizacion.cotizacion_detail, name='cotizacion_detail'),
    path('cotizacion/delete/<int:pk>', cotizacion.cotizacion_delete, name='cotizacion_delete'),
    path('flete/list/', flete.flete_list, name='flete_list'),
    path('flete/create/', flete.flete_create, name='flete_create'),
    path('flete/update/<int:pk>', flete.flete_update, name='flete_update'),
    path('flete/detail/<int:pk>', flete.flete_detail, name='flete_detail'),
    path('flete/delete/<int:pk>', flete.flete_delete, name='flete_delete'),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('cliente/', include('cliente.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/core/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('about_us/', views.about, name='about_us'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(template_name='core/logout.html'), name='logout'),
    path('register/', views.CustomRegisterView.as_view(), name='register'),
    path('profile/', views.UpdateProfileView.as_view(), name='profile'),
]

src/core/models.py
from django.db import models
from django.contrib.auth.models import User



class Usuario(User):
    nombre = models.CharField(max_length=255)
    apellido = models.CharField(max_length=255)
    direccion = models.CharField(max_length=255)
    telefono = models.PositiveIntegerField()

    def __str__(self):
        return f'{self.nombre} - {self.apellido} - {self.telefono} - {self.direccion}'

    

src/core/forms.py
from typing import Any

from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = AuthenticationForm
        fields = ['username', 'password']


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
        help_texts = {'username': ''}

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.fields['password1'].help_text = ''
        self.fields['password2'].help_text = ''


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

src/core/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required,login_not_required  # type: ignore
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView, ListView, DeleteView
from .forms import CustomAuthenticationForm, CustomUserCreationForm, UserProfileForm
from django.db.models import Q


@login_not_required
def index(request):
    return render(request, 'core/index.html')


@login_not_required
def about(request):
    return render(request, 'core/about.html')

@login_not_required
def about_us(request):
    return render(request, 'core/about_us.html')


class CustomLoginView(LoginView):
    authentication_form = CustomAuthenticationForm
    template_name = 'core/login.html'
    next_page = reverse_lazy('core:index')

    def form_valid(self, form: AuthenticationForm) -> HttpResponse:
        usuario = form.get_user()
        messages.success(
            self.request, f'Inicio de sesión exitoso ¡Bienvenido {usuario.username}!'
        )
        return super().form_valid(form)


@method_decorator(login_not_required, name='dispatch')
class CustomRegisterView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'core/register.html'
    success_url = reverse_lazy('core:login')

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        messages.success(self.request, 'Registro exitoso. Ahora puedes iniciar sesión.')
        return super().form_valid(form)


class UpdateProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'core/profile.html'
    success_url = reverse_lazy('core:index')

    def get_object(self):
        # Devuelve el usuario actual en lugar de esperar un pk
        return self.request.user
    

src/core/templates/core/about.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
    
<h1 style="text-align: center;">Acerca de mí</h1>

<div style="text-align: center;">
<img src="{% static 'core/img/about.jpg' %}" alt="" height="200">
</div>
<p>Mi nombre es Gonzalo Peralta, soy estudiante inicial del lenguaje python a lo largo de este curso hemos aprendido a usar el framework Django. 
    En esta oportunidad he realizado una aplicación de gestión de solicitud y cotización de fletes.
</p>

<div style="text-align: center;">
    <a href="https://www.linkedin.com/in/gonzalo-ezequiel-peralta-a55b44161/" class="boton">Linkedin</a>
</div>

<div style="text-align: center;">
<a href="{% url 'core:index' %}">Volver a inicio</a>
</div>


{% endblock content %}

src/core/templates/core/about_us.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
<div style="text-align: center;">
    
<img src="{% static 'core/img/banner2.png' %}" alt="" height="500" width="550">
</div>

<p style="text-align: center;">Somos una agencia dedicada al traslado de paquetes como de personas, no dudes en contactar nuestro servicio</p>

<div style="text-align: center;">
<a href="{% url 'core:index' %}">Volver a inicio</a>
</div>
{% endblock content %}

src/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestión de Fletes</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/milligram/1.4.1/milligram.css">
</head>
<body>
    {% block content %}
        
    {% endblock content %}
</body>
</html>

src/core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
<div style="text-align: center;">
<img src="{% static 'core/img/banner.png' %}" alt="" height="500" width="300">
</div>
<div>
    {% if user.is_authenticated %}
        <div style="text-align: center;">
        <a href="{% url 'cliente:index' %}"><button>Ir a Fletes</button></a>
        <form action="{% url 'core:logout' %}" method="post">
            {% csrf_token %}
        </div>
        <div style="text-align: center;">
        <a href="{% url 'core:logout' %}"><button type="submit">Cerrar Sesión</button></a> 
        </div>
        </form>
        <div style="text-align: center;">
        <a href="{% url 'core:profile' %}">
            <button>Mi Perfil</button>
        </a>
        </div>
        {% else %}
        <div style="text-align: center;">
            <a href="{% url 'core:login' %}"><button>Iniciar Sesión</button></a>   
        </div>    
            {% endif %}
        <div style="text-align: center;">
            <a href="{% url 'core:about' %}">Acerca de mí</a>
        </div>
        <div style="text-align: center;">
            <a href="{% url 'core:about_us' %}">Nosotros</a>
        </div>
</div>
    <div style="text-align: center;">
    {% for message in messages %}
        <p> {{ message }} </p>
    {% endfor %}
    </div>
    <div style="text-align: center;">
        <p>&copy;Aplicación de logística y gestión de fletes hecha en CoderHouse</p>
    </div>

{% endblock content %}

src/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block content %}
    <h1>Iniciar Sesión</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Iniciar Sesión</button>
    </form>
    <p>¿No tienes una cuenta? <a href="{% url 'core:register' %}">Regístrate aquí</a></p>
{% endblock content %}

src/core/templates/core/logout.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 style="text-align: center;">Sesión cerrada</h1>
    <p style="text-align: center;">Has cerrado tu sesión correctamente.</p>
    
    <div style="text-align: center;">

    <a href="{% url 'core:login' %}" class="boton">Volver a Iniciar Sesión</a>
    </div>

    <div style="text-align: center;">
    <a href="{% url 'core:index' %}">Volver a inicio</a>
    </div>
    {% endblock content %}

src/core/templates/core/profile.html
{% extends 'core/base.html' %}

{% block content %}
    <h1>Actualizar perfil de usuario</h1>    
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar Cambios</button>
    </form>

{% endblock content %}

src/core/templates/core/register.html
{% extends 'core/base.html' %}

{% block content %}
    <h1>Registro de Usuario</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit"> Registrarse </button>
    </form>
{% endblock content %}  